#! /usr/bin/python
import urllib
import scriptine.shell


def download_command(quoted):
	url = urllib.unquote(quoted)
	scriptine.shell.call(['curl', '-O', url])

if __name__ == '__main__':
		scriptine.run()


